=== yesskenn/yessiraya_portfolio/cisw440/kenney-final-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:annotation>
<xs:documentation> This XML schema will be used to validate the records in the property listings.
</xs:documentation>
</xs:annotation>

<xs:element name="Listings">
    <xs:complexType>
    <xs:sequence>
    <xs:element name="Property" type="propertyList" maxOccurs="unbounded">
        <xs:annotation>
        <xs:documentation>
        This represents for the property listing record. There is more than one property listing.
        The HOA column can only be yes or no values.
        </xs:documentation>
        </xs:annotation>

    <xs:complexType>
        <xs:sequence>
    
        <xs:element name="propertyID"
            type="text"/>
        <xs:element name="city"
            type="text"/>
        <xs:element name="price"
            type="text"/>
        <xs:element name="bedBath"
        type="text"/>
        <xs:element name="lotSize"
            type="text"/>
        <xs:element name="yearBuilt"
            type="text"/>
        <xs:element name="features"
            type="text"/>
        <xs:element name="hasHoa"
            type="text"/>
    
        </xs:sequence>
    </xs:complexType>
    </xs:element>
    </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== yesskenn/yessiraya_portfolio/cisw440/kenney-final-project.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="kenney-final-styles.xsl"?>
<!DOCTYPE note [
    <!ENTITY sac "Sacramento">
    <!ENTITY org "Orangevale">
    <!ENTITY rock "Rocklin">
    <!ENTITY fol "Folsom">
    <!ENTITY elk "Elk Grove">]>

<Listings xmlns:xsi="http://www.w3.org/2001.XMLSchema-instance" xsi:noNamespaceSchemaLocation="kenney-final-schema.xsd">
    <Property>
        <propertyID>110101</propertyID>
        <city>&rock;</city>
        <price>$636,900</price>
        <bedBath>5bd/3ba</bedBath>
        <lotSize>5236sqft</lotSize>
        <yearBuilt>1989</yearBuilt>
        <features>Formal living/dining room, contemporary style</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>111002</propertyID>
        <city>&sac;</city>
        <price>$789,000</price>
        <bedBath>3bd/3ba</bedBath>
        <lotSize>0.26acres</lotSize>
        <yearBuilt>1950</yearBuilt>
        <features>Two fireplaces, attached garage, quartz</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>110103</propertyID>
        <city>&elk;</city>
        <price>$769,900</price>
        <bedBath>4bd/3ba</bedBath>
        <lotSize>7884sqft</lotSize>
        <yearBuilt>2004</yearBuilt>
        <features>Marble counters, spacious primary suite, BBQ island</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>110104</propertyID>
        <city>&elk;</city>
        <price>$649,000</price>
        <bedBath>4bd/3ba</bedBath>
        <lotSize>3563sqft</lotSize>
        <yearBuilt>2016</yearBuilt>
        <features>Kitchen island, breakfast nook, automatic sprinklers</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>110105</propertyID>
        <city>&fol;</city>
        <price>$574,000</price>
        <bedBath>3bd/2ba</bedBath>
        <lotSize>7087sqft</lotSize>
        <yearBuilt>1959</yearBuilt>
        <features>Half-circular driveway, near scenic trails</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>110106</propertyID>
        <city>&sac;</city>
        <price>$838,000</price>
        <bedBath>3bd/1ba</bedBath>
        <lotSize>7497sqft</lotSize>
        <yearBuilt>1934</yearBuilt>
        <features>Spa oasis, updated kitchen, covered deck, Tudor style</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>110107</propertyID>
        <city>&sac;</city>
        <price>$538,000</price>
        <bedBath>3bd/2ba</bedBath>
        <lotSize>3920sqft</lotSize>
        <yearBuilt>1974</yearBuilt>
        <features>Close to shopping, recently renovated</features>
        <hasHoa ID="hoa">Yes</hasHoa>
    </Property>
    <Property>
        <propertyID>110108</propertyID>
        <city>&org;</city>
        <price>$835,000</price>
        <bedBath>3bd/3ba</bedBath>
        <lotSize>2.5acres</lotSize>
        <yearBuilt>1955</yearBuilt>
        <features>Pool, Pool house</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>110109</propertyID>
        <city>Citrus Heights</city>
        <price>$600,000</price>
        <bedBath>3bd/2ba</bedBath>
        <lotSize>2.3acres</lotSize>
        <yearBuilt>2001</yearBuilt>
        <features>Seasonal creek, wrap-around porch, fruit trees</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>110110</propertyID>
        <city>Citrus Heights</city>
        <price>$470,000</price>
        <bedBath>3bd/2ba</bedBath>
        <lotSize>7840sqft</lotSize>
        <yearBuilt>1957</yearBuilt>
        <features>Expansive backyard, shed</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>221001</propertyID>
        <city>Carmichael</city>
        <price>$699,000</price>
        <bedBath>4bd/3ba</bedBath>
        <lotSize>0.25acres</lotSize>
        <yearBuilt>1954</yearBuilt>
        <features>Pool, wood floors, owned solar</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>221002</propertyID>
        <city>Cameron Park</city>
        <price>$675,000</price>
        <bedBath>4bd/3ba</bedBath>
        <lotSize>0.36acres</lotSize>
        <yearBuilt>2019</yearBuilt>
        <features>Spa-like primary suite, walk-in pantry</features>
        <hasHoa ID="hoa">Yes</hasHoa>
    </Property>
    <Property>
        <propertyID>221003</propertyID>
        <city>&fol;</city>
        <price>$749,999</price>
        <bedBath>3bd/3ba</bedBath>
        <lotSize>8783sqft</lotSize>
        <yearBuilt>1987</yearBuilt>
        <features>Auto sprinkler, corner lot, breakfast area</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>221004</propertyID>
        <city>&fol;</city>
        <price>$640,000</price>
        <bedBath>4bd/3ba</bedBath>
        <lotSize>3311sqft</lotSize>
        <yearBuilt>2022</yearBuilt>
        <features>New construction, high-end finishes, open layout</features>
        <hasHoa ID="hoa">Yes</hasHoa>
    </Property>
    <Property>
        <propertyID>221005</propertyID>
        <city>Fiddletown</city>
        <price>$589,000</price>
        <bedBath>4bd/2ba</bedBath>
        <lotSize>10.14acres</lotSize>
        <yearBuilt>1990</yearBuilt>
        <features>Chicken coop, greenhouse, farmhouse-style kitchen</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>221006</propertyID>
        <city>&fol;</city>
        <price>$550,000</price>
        <bedBath>2bd/1ba</bedBath>
        <lotSize>7000sqft</lotSize>
        <yearBuilt>1950</yearBuilt>
        <features>Cute house, in historic &fol;</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>221007</propertyID>
        <city>&sac;</city>
        <price>$629,000</price>
        <bedBath>3bds/2ba</bedBath>
        <lotSize>6534sqft</lotSize>
        <yearBuilt>1950</yearBuilt>
        <features>Fireplace, near shopping, Add-on den/studio</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>221008</propertyID>
        <city>&elk;</city>
        <price>$800,000</price>
        <bedBath>3bd/2ba</bedBath>
        <lotSize>2.65acres</lotSize>
        <yearBuilt>1974</yearBuilt>
        <features>Barn, mature trees, ranch style</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>221009</propertyID>
        <city>&rock;</city>
        <price>$850,000</price>
        <bedBath>3bd/2ba</bedBath>
        <lotSize>0.32acres</lotSize>
        <yearBuilt>1987</yearBuilt>
        <features>Owned solar, Open floor plan</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>221010</propertyID>
        <city>Roseville</city>
        <price>$680,000</price>
        <bedBath>3bd/2ba</bedBath>
        <lotSize>7131sqft</lotSize>
        <yearBuilt>1978</yearBuilt>
        <features>Spa, pool, bright and airy</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>330101</propertyID>
        <city>&rock;</city>
        <price>$639,000</price>
        <bedBath>3bd/3ba</bedBath>
        <lotSize>3459sqft</lotSize>
        <yearBuilt>2019</yearBuilt>
        <features>Pool, pet door, Bright open kitchen</features>
        <hasHoa ID="hoa">Yes</hasHoa>
    </Property>
    <Property>
        <propertyID>330102</propertyID>
        <city>Lincoln</city>
        <price>$499,999</price>
        <bedBath>3bd/3ba</bedBath>
        <lotSize>5663sqft</lotSize>
        <yearBuilt>1982</yearBuilt>
        <features>Alley access, large kitchen, fully fenced</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>330103</propertyID>
        <city>Rescue</city>
        <price>$699,995</price>
        <bedBath>3bd/2ba</bedBath>
        <lotSize>2.21acres</lotSize>
        <yearBuilt>1986</yearBuilt>
        <features>Pool, 3.5 car garage, </features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>330104</propertyID>
        <city>&rock;</city>
        <price>$434,300</price>
        <bedBath>2bd/1ba</bedBath>
        <lotSize>10267sqft</lotSize>
        <yearBuilt>1949</yearBuilt>
        <features>Spacious lot, remodeled bathroom, new cabinetry</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>330105</propertyID>
        <city>Auburn</city>
        <price>$559,900</price>
        <bedBath>3bd/2ba</bedBath>
        <lotSize>0.29acres</lotSize>
        <yearBuilt>1949</yearBuilt>
        <features>Back deck, den with private entrance, pellet stove</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>330106</propertyID>
        <city>Cameron Park</city>
        <price>$633,900</price>
        <bedBath>4bd/2ba</bedBath>
        <lotSize>0.47acres</lotSize>
        <yearBuilt>2003</yearBuilt>
        <features>3-car garage, outdoor access, near shopping</features>
        <hasHoa ID="hoa">No</hasHoa>
    </Property>
    <Property>
        <propertyID>330107</propertyID>
        <city>Fair Oaks</city>
        <price>$499,000</price>
        <bedBath>3bd/2ba</bedBath>
        <lotSize>0.25acres</lotSize>
        <yearBuilt>1956</yearBuilt>
        <features>Peaceful neighborhood, updated kitched, ADU</features>
