=== yesskenn/yessiraya_portfolio/cisw440/kenney-week05-labassign.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:annotation>
<xs:documentation>This XML Schema will be used to validate the Patient Records
of the office visits log.
</xs:documentation>
</xs:annotation>
<xs:element name="Records">
<xs:element name="Patient">
    <xs:complexType>
    <xs:sequence>
    <xs:element name="ID"
        type="integer"/>

    <xs:element name="FullName"
        type="string"/>

    <xs:element name="DOB"
        type="xs:date"/>

    <xs:element name="Gender"
        type="string"/>

    <xs:element name="ServiceDate"
        type="xs:date"/>

    <xs:element name="ProcedureCode"
        type="integer"/>

    <xs:element name="PrimaryDiagnosis"
        type="string"/> 
    </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:element>
</xs:schema>

=== yesskenn/yessiraya_portfolio/cisw440/kenney-week05-lab.xml
<?xml version="1.0" encoding="UTF-8"?>

 <Records xmlns:xsi="http://www.w3.org/2002/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="kenney-week05-labassign.xsd">
    <Patient>
        <ID>1</ID>
        <FullName>John Doe</FullName>
        <DOB>1987/3/2</DOB>
        <Gender>Male</Gender>
        <ServiceDate>2016/4/5</ServiceDate>
        <ProcedureCode>99215</ProcedureCode>
        <PrimaryDiagnosis>R51</PrimaryDiagnosis>
    </Patient>
    <Patient>
        <ID>2</ID>
        <FullName>Jane Doe</FullName>
        <DOB>1977/7/13</DOB>
        <Gender>Female</Gender>
        <ServiceDate>2016/2/3</ServiceDate>
        <ProcedureCode>99213</ProcedureCode>
        <PrimaryDiagnosis>Z34.0</PrimaryDiagnosis>
    </Patient>
    <Patient>
        <ID>3</ID>
        <FullName>Jackie Chan</FullName>
        <DOB>2010/9/23</DOB>
        <Gender>Male</Gender>
        <ServiceDate>2016/10/5</ServiceDate>
        <ProcedureCode>99214</ProcedureCode>
        <PrimaryDiagnosis>S92.302A</PrimaryDiagnosis>
    </Patient>
    <Patient>
        <ID>4</ID>
        <FullName>Chuck Norris</FullName>
        <DOB>2015/5/15</DOB>
        <Gender>Male</Gender>
        <ServiceDate>2016/8/12</ServiceDate>
        <ProcedureCode>99283</ProcedureCode>
        <PrimaryDiagnosis>813.80</PrimaryDiagnosis>
    </Patient>
    <Patient>
        <ID>5</ID>
        <FullName>Bruce Lee</FullName>
        <DOB>1934/1/2</DOB>
        <Gender>Male</Gender>
        <ServiceDate>2014/2/6</ServiceDate>
        <ProcedureCode>99202</ProcedureCode>
        <PrimaryDiagnosis>R51</PrimaryDiagnosis>
    </Patient>
    <Patient>
        <ID>6</ID>
        <FullName>Monica Latte</FullName>
        <DOB>1950/4/4</DOB>
        <Gender>Female</Gender>
        <ServiceDate>2015/12/31</ServiceDate>
        <ProcedureCode>99208</ProcedureCode>
        <PrimaryDiagnosis>V20.0</PrimaryDiagnosis>
    </Patient>
</Records>
